- name: create Azure resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: '{{ location }}'
    state: present

- name: create Azure virtual network in resource group
  azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ resource_group }}"
    address_prefixes_cidr:
    - 192.168.0.0/24
    state: present

- name: create Azure subnet in virtualnetwork
  azure_rm_subnet:
    name: '{{ subnet_name }}'
    state: present
    virtual_network_name: "{{ vnet_name }}"
    resource_group: "{{ resource_group }}"
    address_prefix_cidr: 192.168.0.0/24

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ subnet_name }}"

- name: create Azure storage account
  azure_rm_storageaccount:
    name: '{{ storage_name }}'
    resource_group: "{{ resource_group }}"
    account_type: Standard_LRS

