- name: create Azure vm extension to enable HTTPS WinRM listener
  with_items: '{{ instances }}'
  azure_rm_virtualmachineextension:
    name: winrm-extension
    resource_group: "{{ resource_group }}"
    virtual_machine_name: "{{ item }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
    auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
    timeout: 60

